### ISSUE TITLE
setup instructions to integrate  aws ses to gitlab smtp.

### ISSUE THREAD

**Issue by Govardhannew** [aidansteele/ses-sidecar#1]
Hi @aidansteele 

we need to use this setup for integrating aws ses with gitlab:https://docs.gitlab.com/omnibus/settings/smtp.html. could you please let us know how we proceed to setup this. we already have a verified identity.

**Comment by aidansteele** [comment]
Hi @Govardhannew

It's hard to provide exact instructions on how to set this up without knowing more information about how you are running GitLab (e.g. On an EC2 instance? Or ECS? Or Kubernetes? etc).

It is likely that the configuration will be similar to the _SMTP without SSL_ example in the docs link you shared. E.g.:

```ruby
gitlab_rails['smtp_enable'] = true
gitlab_rails['smtp_address'] = 'localhost' # assuming you run ses-sidecar on the same EC2 instance
gitlab_rails['smtp_port'] = 1025 # assuming you run ses-sidecar on the default port 1025
gitlab_rails['smtp_domain'] = 'localhost'
gitlab_rails['smtp_tls'] = false
gitlab_rails['smtp_openssl_verify_mode'] = 'none'
gitlab_rails['smtp_enable_starttls_auto'] = false
gitlab_rails['smtp_ssl'] = false
gitlab_rails['smtp_force_ssl'] = false
```

**Comment by Govardhannew** [comment]
@aidansteele 

we are running in ec2 instance. Our SES managed service is running in AWS global partition as it is not available in china partition. Ec2 is running in AWS china partition.  Is it possible to use this solution in our scenario?.

**Comment by aidansteele** [comment]
Ah I see. In that case I think this solution won't work because you can't use a role across AWS partitions. You will have to use the standard SES SMTP support with SES SMTP credentials: https://aws.amazon.com/premiumsupport/knowledge-center/ses-create-smtp-credentials/

**Comment by Govardhannew** [comment]
ya got it. This can be utilized only if SES and EC2 are in same partition?. unfortunately SES is not yet available in China partition.
